export const RouteNames = {
  HOME: "/",
  STATISTIKA: "/statistics",
  CURRENT_REPAIR: "/current-repair",
  VU_31: "/statistics/vu-31",
  VU_10: "/statistics/vu-10",
  CREATE: (id) => id + "/create",
  VU_36: "/statistics/vu-36",
  FRAZA: "/statistics/fraza",
  VU_36_CURRENT: "/current-repair/vu-36",
  VU_31_CURRENT: "/current-repair/vu-31",
  VU_31_COLLECTOR: "/collector-vu-23",
  SIGNATURE: "/signatures-list",
  REPORT: "/report",
  STATISTIKAARCHIVE: "/statistics/archive",
  ASSEMBLY: "/assembly-unit",
  AUTO_BRAKES: "/auto-brakes",
  VU_22: "/auto-brakes/vu-22",
  VU_47: "/auto-brakes/vu-47",
  REGISTER_AUTO: "/auto-brakes/register-auto",
  REGISTER_REGULAR: "/auto-brakes/register-regular",
  REGISTER_RUKVAS: "/auto-brakes/register-rukvas",
  REGISTER_22: "/auto-brakes/vu-22",
  REGISTER_BRAKES: "/auto-brakes/register-brake-silindir",
  REGISTER_RAZOBSHITEL: "/auto-brakes/register-rozobshitel",
  REGISTER_EXITENTRY: "/auto-brakes/entry-exit-control",
  AUTOMOBILE_UNIT: "/automobile-unit",
  EQUIPMENT_UNIT: "/equipment-unit",
  DEFECTOSCOPES: "/defectoscopes",
  CARRIAGE_UNIT: "/carriage-unit",
  CARRIAGE_UNIT_FRAZA: "/carriage-unit/fraza",
  VU_22_Arava: "/carriage-unit/vu-22",
  CARRIAGE_UNIT_DEED: "/carriage-unit/entry-exit-control",
  VU_32: "/carriage-unit/vu-32",
  PRO_UNIT: "/pto-unit",
  LOGIN: "/login",
  WHEEL_PAIRS: "/wheel-pairs",
  CARRIAGE: "/defectoscopes/carriage",
  WHEEL: "/defectoscopes/wheel",
  ACTS: "acts",

  NOT_FOUND: "*",
};
